backend:
  name: github
  repo: jaudat150/qweriohadsfaqwer
  branch: main
  # Remove client_id and client_secret if you switch to Netlify Identity (recommended)

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "site_config"
        label: "Homepage Settings"
        file: "site.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Button Color", name: "primary_color", widget: "color" }